"""empty message

Revision ID: d08b60c1d1d6
Revises: 7cae4f4fa42d
Create Date: 2018-02-20 05:52:06.080599

"""

# revision identifiers, used by Alembic.
revision = 'd08b60c1d1d6'
down_revision = '7cae4f4fa42d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
import sqlalchemy_jsonfield

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga_releases', sa.Column('phash_duplicate', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga_releases', 'phash_duplicate')
    # ### end Alembic commands ###
