"""empty message

Revision ID: e786b3d63f9b
Revises: d08b60c1d1d6
Create Date: 2018-02-20 05:56:33.334126

"""

# revision identifiers, used by Alembic.
revision = 'e786b3d63f9b'
down_revision = 'd08b60c1d1d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils
import sqlalchemy_jsonfield

# Patch in knowledge of the citext type, so it reflects properly.
from sqlalchemy.dialects.postgresql.base import ischema_names
import citext
import queue
import datetime
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.dialects.postgresql import JSON
from sqlalchemy.dialects.postgresql import TSVECTOR
ischema_names['citext'] = citext.CIText



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga_releases', sa.Column('uploaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manga_releases', 'uploaded')
    # ### end Alembic commands ###
